# Configuration for sensor deployment

# Enable the filesystem logging backend
CONFIG_LOG_BACKEND_FS=y
CONFIG_LOG_BACKEND_FS_FILES_LIMIT=60 # 256kB partition for log, 60 * 4096 < 256kB
CONFIG_LOG_BACKEND_FS_DIR="/log"

